# -*- mode: ruby -*-
# vi: set ft=ruby :

# check with ifconfig/ipconfig, "look for Ethernet-Adapter VirtualBox Host-Only Network", choose on in that ip range
CONTROL_IP = "192.168.56.80"
# the private LAN for inter-node communication - this has to be an unique class b network (look at you openvpn subnets too)
KUBE_NETWORK = "10.244.0.0/16"
# kubeadm token generate , used to join members to the kubernets cluster
TOKEN = "qn265f.czo0oiw8o2q5pb7n"
ENABLE_APT_CAHE = "false"
LOCAL_APT_CACHE_URL = "http://192.168.178.41:3142"

Vagrant.configure("2") do |config|
   config.vm.box = "generic/ubuntu2204"
   config.vm.hostname = "ranger"
   config.vm.box_check_update = false
   config.vm.network "private_network", ip: CONTROL_IP # <-- Host-Only network to have a static ip to use kubectl on you guest os

   config.vm.disk :disk, size: "50GB", primary: true

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "4098"
     vb.cpus = 4
     vb.name = "kubernets"
   end

   config.vm.provision "file", source: "control.yml", destination: "/home/vagrant/control.yml"
   config.vm.provision "file", source: "kube-flannel.yml", destination: "/home/vagrant/kube-flannel.yml"

   config.vm.provision :shell do |s|
      s.path = 'setup-system.sh'
   end

   config.vm.provision :shell do |s|
     s.env = {LOCAL_APT_CACHE_URL:LOCAL_APT_CACHE_URL, ENABLE_APT_CAHE:ENABLE_APT_CAHE}
     s.path = 'setup-packages.sh'
   end

   config.vm.provision :shell do |s|
      s.env = {CONTROL_IP:CONTROL_IP, TOKEN:TOKEN, KUBE_NETWORK: KUBE_NETWORK}
      s.path = 'setup-ranger.sh'
      s.privileged = false
   end
end
