# -*- mode: ruby -*-
# vi: set ft=ruby :

# check with ifconfig/ipconfig, "look for Ethernet-Adapter VirtualBox Host-Only Network", choose on in that ip range
CONTROL_IP = "192.168.56.100"
# the private LAN for inter-node communication - this has to be an unique class b network (look at you openvpn subnets too)
KUBE_NETWORK = "10.10.0.0/16"
# kubeadm token generate , used to join members to the kubernets cluster
TOKEN = "qn265f.czo0oiw8o2q5pb7n"
PUBLIC_IP = "192.168.178.37"

Vagrant.configure("2") do |config|
   config.vm.box = "generic/ubuntu2004"
   #config.vm.box = "generic/ubuntu1804" <-- still recommended by google ...
   config.vm.hostname = "kube"
   config.vm.box_check_update = false
   config.vm.network "forwarded_port", guest: 6443, host: 6443, host_ip: "127.0.0.1" # <-- simple way to connet to NAT network, needed for internet connection (apt/docker)
   config.vm.network "private_network", ip: CONTROL_IP # <-- Host-Only network to have a static ip to use kubectl on you guest os

   config.vm.disk :disk, size: "50GB", primary: true

   config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "4098"
     vb.cpus = 4
     vb.name = "kubernets"
   end

   config.vm.provision "file", source: "control.yml", destination: "/home/vagrant/control.yml"

   config.vm.provision :shell do |s|
      s.path = 'setup-system.sh'
   end

   config.vm.provision :shell do |s|
     s.path = 'setup-packages.sh'
   end

   config.vm.provision :shell do |s|
      s.env = {CONTROL_IP:CONTROL_IP, TOKEN:TOKEN, PUBLIC_IP: PUBLIC_IP, KUBE_NETWORK: KUBE_NETWORK}
      s.path = 'setup-kubernets-controlnode.sh'
   end
end
